### ISSUE TITLE
Update README.md to avoid Hidden bug about commitID 

### ISSUE THREAD

**Issue by HuGanghui** [checkstyle/patch-filters#59] opened 2020-06-30 10:21 UTC
As mentioned in https://github.com/checkstyle/patch-filters/issues/21#issuecomment-651468699, we need to update README.md——modifying projects-to-test-on.properties, remove specific version in project(for example in guava, remove `v28.2`, change `guava|git|https://github.com/google/guava|v28.2||` to `guava|git|https://github.com/google/guava||`) to avoid Hidden bug about commitID

**Comment by rdiachenko** [comment] 2020-06-30 20:55
It's not a bug. Please check my comment - https://github.com/checkstyle/patch-filters/issues/21#issuecomment-652035703
You should not rely on manual checkout but use projects-to-test-on.properties and specify commit hash there to make diff.groovy do checkout automatically for you.

Closed.

**Comment by rdiachenko** [comment] 2020-07-01 21:13
Reopened due to https://github.com/checkstyle/patch-filters/issues/21#issuecomment-652145860

**Comment by rdiachenko** [comment] 2020-07-02 09:04
The fix was merged.

**Closed by rdiachenko** 2020-07-02 09:04 UTC
