### ISSUE TITLE
use system variable to customize path patch

### ISSUE THREAD

**Issue by romani** [checkstyle/patch-filters#34] opened 2020-06-23 14:06 UTC
https://github.com/checkstyle/patch-filters/blob/952acf172a30af4d3876921e24c9974c4183a41d/src/main/resources/patchConfig.xml#L20-L22

please use system example: 
`<property name="headerFile" value="${checkstyle.header.file}"/>`

you define system variables in IDE Run/Debug configuration of comamndline `-Dcheckstyle.header.file=.... `

**Comment by HuGanghui** [comment] 2020-06-24 08:22
@romani I am not clear where to add -Dchecksytle.patch.file=/Users/hgh/Documents/GitHub/patch-filters/DiffReport/patch.txt, I try 
<img width="994" alt="image" src="https://user-images.githubusercontent.com/50866227/85521478-e2560980-b636-11ea-8928-4eb0e4c81f15.png">

**Comment by rdiachenko** [comment] 2020-06-24 14:20
@HuGanghui have you checked IntellijIdea doc? (https://www.jetbrains.com/help/objc/add-environment-variables-and-program-arguments.html)
It should be an environment variable. How did you specify it and what didn't work?

**Comment by romani** [comment] 2020-06-24 15:03
it could be program argument but in main method need to convert it system variable by https://stackoverflow.com/a/11101130/1015848

or you can put system variable to "VM options" (not environment variables) as `-Dcheckstyle.pathfilter.patch=....` and use the same name variable in config.

**Comment by HuGanghui** [comment] 2020-06-25 03:18
@romani, I try 
> it could be program argument but in main method need to convert it system variable by 
> https://stackoverflow.com/a/11101130/1015848

but it is still not ok
set program arguments:
<img width="977" alt="image" src="https://user-images.githubusercontent.com/50866227/85649298-5e069380-b6d5-11ea-9a3c-6ccc410bfe02.png">


set system variable in main method:
```java
        final String previousValue = System.setProperty("checkstyle.pathfilter.patch", args[7]);
```
config in patchConfig:
```xml
<module name="com.puppycrawl.tools.checkstyle.filters.SuppressionPatchFilter">
        <!--<property name="file" value="/Users/hgh/Documents/GitHub/patch-filters/DiffReport/patch.txt"/>-->
        <property name="file" value="${checkstyle.pathfilter.patch}"/>
    </module>
```
and 
> or you can put system variable to "VM options" (not environment variables) as -Dcheckstyle.pathfilter.patch=.... and use the > same name variable in config.
it is also not ok

**Comment by HuGanghui** [comment] 2020-06-25 04:35
@rdiachenko I try environment variable, it also not works.

<img width="981" alt="image" src="https://user-images.githubusercontent.com/50866227/85653947-4680d800-b6e0-11ea-9c47-0754b9138a47.png">

```xml
<module name="com.puppycrawl.tools.checkstyle.filters.SuppressionPatchFilter">
        <!--<property name="file" value="/Users/hgh/Documents/GitHub/patch-filters/DiffReport/patch.txt"/>-->
        <property name="file" value="${checkstyle.pathfilter.patch}"/>
    </module>
```

**Comment by rdiachenko** [comment] 2020-06-25 22:00
I doubt it will work via IDE. That config goes as input to `diff.groovy` which uses `maven-checkstyle-plugin` to launch checkstyle against specified project. As far as I remember `maven-checkstyle-plugin` can't replace placeholders in checkstyle config unless you configure this explicitly via `<propertyExpansion>checkstyle.pathfilter.patch=${checkstyle.pathfilter.patch.from.env}</propertyExpansion>` or https://maven.apache.org/plugins/maven-checkstyle-plugin/check-mojo.html#propertiesLocation. However, I haven't tried the second option with `propertiesLocation`.

**Comment by HuGanghui** [comment] 2020-06-30 09:20
@rdiachenko 
1.   add `<propertyExpansion>checkstyle.pathfilter.patch=${checkstyle.pathfilter.patch.from.env}</propertyExpansion>` to contribution/checkstyle-tester/pom.xml
2. change patchConfig 
```xml
 <module name="com.puppycrawl.tools.checkstyle.filters.SuppressionPatchFilter">
        <property name="file" value="${checkstyle.pathfilter.patch}"/>
    </module>
```
3. set checkstyle.pathfilter.patch.from.env as environment variable.

<img width="981" alt="image" src="https://user-images.githubusercontent.com/50866227/86108409-b387d980-baf5-11ea-99d1-d4ec9cfcef68.png">

4. run `GeneratePatchFileLauncher` to test, and it's not work, here is error information:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project sample: Error during page generation: Error rendering Maven report: Failed during checkstyle execution: Failed during checkstyle configuration: unable to parse configuration stream: Property ${checkstyle.pathfilter.patch} has not been set -> [Help 1]
```

Please let me know if I am incorrect

**Comment by rdiachenko** [comment] 2020-06-30 21:41
@HuGanghui the approach with `propertyExpansion` works fine on my local, just checked it.

Steps you provided above is a good example and it helps to see where your problems are. Keep it up!

**Tip:** the problem is in the step 1. Please read checkstyle maven plugin doc - https://maven.apache.org/plugins/maven-checkstyle-plugin/index.html and fix the problem yourself.

**Comment by HuGanghui** [comment] 2020-07-01 03:25
@rdiachenko I try it, and it work now, thanks, do we need to make a PR to change 

```
<module name="com.puppycrawl.tools.checkstyle.filters.SuppressionPatchFilter">
        <property name="file" value="/Users/hgh/Documents/GitHub/patch-filters/DiffReport/patch.txt"/>
    </module>
```
to

```
<module name="com.puppycrawl.tools.checkstyle.filters.SuppressionPatchFilter">
        <property name="file" value="${checkstyle.pathfilter.patch}"/>
    </module>
```
and update README.md?

**Comment by rdiachenko** [comment] 2020-07-01 20:26
@HuGanghui 
1. Update `patchConfig.xml` with `${checkstyle.patchfilter.patch}`
2. Update REAMDE
3. Pull recent changes from `checkstyle/contribution` as soon as this PR is merged - https://github.com/checkstyle/contribution/pull/491

**Comment by rdiachenko** [comment] 2020-07-02 08:46
The fix was merged.

**Closed by rdiachenko** 2020-07-02 08:46 UTC
